# Generated by Django 3.2.20 on 2024-09-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.BigIntegerField(unique=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('cnpj_emitente', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_emitente', models.CharField(blank=True, max_length=255, null=True)),
                ('inscricao_estadual_emitente', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj_destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('inscricao_estadual_destinatario', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('erro', 'Erro'), ('enviado', 'Enviado'), ('processando_autorizacao', 'Processando'), ('erro_autorizacao', 'Não autorizado'), ('autorizado', 'Autorizado'), ('cancelado', 'Cancelado'), ('denegado', 'Denegado'), ('manifestado', 'Manifestado')], max_length=30, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_ncm', models.CharField(blank=True, max_length=255, null=True)),
                ('inclui_no_total', models.CharField(blank=True, max_length=255, null=True)),
                ('cfop', models.CharField(blank=True, max_length=255, null=True)),
                ('unidade_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_unitario_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('icms_origem', models.CharField(blank=True, max_length=255, null=True)),
                ('icms_situacao_tributaria', models.CharField(blank=True, max_length=255, null=True)),
                ('pis_situacao_tributaria', models.CharField(blank=True, max_length=255, null=True)),
                ('cofins_situacao_tributaria', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_frete', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_seguro', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_desconto', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='challenge.invoice', to_field='ref')),
            ],
        ),
    ]
